version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    hostname: bd3b0f979192
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: postgres2
      POSTGRES_DB: school
      LANG: en_US.utf8
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres1 -d school"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres1:postgres2@postgres:5432/school
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run seed && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: